TITLE = "LED Train Ticker"

DOT_SIZE = 6 # Including dot border width
DOT_BORDER_WIDTH = 1

GRID_WIDTH = 210
GRID_HEIGHT = 35

WINDOW_WIDTH = DOT_SIZE * GRID_WIDTH
WINDOW_HEIGHT = DOT_SIZE * GRID_HEIGHT

SUB_WINDOW_WIDTH = 600
SUB_WINDOW_HEIGHT = 400

FONT_SIZE = 10
FONT_SIZE_HEAD = 13